In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [13]:
import pandas as pd
df=pd.read_csv("/content/netflix_titles.csv")

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5351 entries, 0 to 5350
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       5351 non-null   object
 1   type          5351 non-null   object
 2   title         5351 non-null   object
 3   director      5351 non-null   object
 4   cast          5351 non-null   object
 5   country       5351 non-null   object
 6   date_added    5351 non-null   object
 7   release_year  5351 non-null   object
 8   rating        5351 non-null   object
 9   duration      5351 non-null   object
 10  listed_in     5350 non-null   object
 11  description   5334 non-null   object
dtypes: object(12)
memory usage: 501.8+ KB

In [15]:
df.isnull().sum()

show_id          0
type             0
title            0
director         0
cast             0
country          0
date_added       0
release_year     0
rating           0
duration         0
listed_in        1
description     17
dtype: int64

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5351 entries, 0 to 5350
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       5351 non-null   object
 1   type          5351 non-null   object
 2   title         5351 non-null   object
 3   director      5351 non-null   object
 4   cast          5351 non-null   object
 5   country       5351 non-null   object
 6   date_added    5351 non-null   object
 7   release_year  5351 non-null   object
 8   rating        5351 non-null   object
 9   duration      5351 non-null   object
 10  listed_in     5350 non-null   object
 11  description   5334 non-null   object
dtypes: object(12)
memory usage: 501.8+ KB

In [16]:
df.drop_duplicates()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",24-Sep-21,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
1,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,24-Sep-21,2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
2,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,24-Sep-21,2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
3,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis NiewÃ¶hner, Milan Peschel,...","Germany, Czech Republic",23-Sep-21,2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
4,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,21-Sep-21,1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...
...,...,...,...,...,...,...,...,...,...,...,...,...
5346,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,1-Nov-19,2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
5347,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,11-Jan-20,2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
5348,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2-Mar-19,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...
5349,s8808,TV Show,Parasyte: The Grey,Yeon Sang-ho,"Shin Hyun-been, Jeon Yeo-bin, Goo Kyo-hwan",South Korea,5-Apr-24,2024,TV-MA,1 Season,"Sci-fi, Horror, Action",A new breed of parasitic aliens arrive on Eart...
5350,s8809,Movie,Serena,Susanne Bier,"Bradley Cooper, Jennifer Lawrence, Toby Jones,...",United States,5-Apr-24,2014,A,110 min,"Drama, Romance, Thriller","In the 1920s, a newly married couple attempt t..."

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5351 entries, 0 to 5350
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       5351 non-null   object
 1   type          5351 non-null   object
 2   title         5351 non-null   object
 3   director      5351 non-null   object
 4   cast          5351 non-null   object
 5   country       5351 non-null   object
 6   date_added    5351 non-null   object
 7   release_year  5351 non-null   object
 8   rating        5351 non-null   object
 9   duration      5351 non-null   object
 10  listed_in     5350 non-null   object
 11  description   5334 non-null   object
dtypes: object(12)
memory usage: 501.8+ KB

In [18]:
df.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",24-Sep-21,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
1,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,24-Sep-21,2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
2,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,24-Sep-21,2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
3,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis NiewÃ¶hner, Milan Peschel,...","Germany, Czech Republic",23-Sep-21,2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
4,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,21-Sep-21,1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...

In [28]:
df.dropna()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",24-Sep-21,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
1,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,24-Sep-21,2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
2,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,24-Sep-21,2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
3,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis NiewÃ¶hner, Milan Peschel,...","Germany, Czech Republic",23-Sep-21,2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
4,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,21-Sep-21,1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...
...,...,...,...,...,...,...,...,...,...,...,...,...
5346,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,1-Nov-19,2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
5347,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,11-Jan-20,2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
5348,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2-Mar-19,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...
5349,s8808,TV Show,Parasyte: The Grey,Yeon Sang-ho,"Shin Hyun-been, Jeon Yeo-bin, Goo Kyo-hwan",South Korea,5-Apr-24,2024,TV-MA,1 Season,"Sci-fi, Horror, Action",A new breed of parasitic aliens arrive on Eart...
5350,s8809,Movie,Serena,Susanne Bier,"Bradley Cooper, Jennifer Lawrence, Toby Jones,...",United States,5-Apr-24,2014,A,110 min,"Drama, Romance, Thriller","In the 1920s, a newly married couple attempt t..."

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5334 entries, 0 to 5350
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       5334 non-null   object
 1   type          5334 non-null   object
 2   title         5334 non-null   object
 3   director      5334 non-null   object
 4   cast          5334 non-null   object
 5   country       5334 non-null   object
 6   date_added    5334 non-null   object
 7   release_year  5334 non-null   object
 8   rating        5334 non-null   object
 9   duration      5334 non-null   object
 10  listed_in     5334 non-null   object
 11  description   5334 non-null   object
dtypes: object(12)
memory usage: 670.8+ KB

In [31]:
df.drop_duplicates()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",24-Sep-21,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
1,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,24-Sep-21,2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
2,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,24-Sep-21,2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
3,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis NiewÃ¶hner, Milan Peschel,...","Germany, Czech Republic",23-Sep-21,2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
4,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,21-Sep-21,1998,TV-14,166 min,"Comedies, International Movies, Romantic Movies",When the father of the man she loves insists t...
...,...,...,...,...,...,...,...,...,...,...,...,...
5346,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,1-Nov-19,2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
5347,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,11-Jan-20,2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
5348,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2-Mar-19,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...
5349,s8808,TV Show,Parasyte: The Grey,Yeon Sang-ho,"Shin Hyun-been, Jeon Yeo-bin, Goo Kyo-hwan",South Korea,5-Apr-24,2024,TV-MA,1 Season,"Sci-fi, Horror, Action",A new breed of parasitic aliens arrive on Eart...
5350,s8809,Movie,Serena,Susanne Bier,"Bradley Cooper, Jennifer Lawrence, Toby Jones,...",United States,5-Apr-24,2014,A,110 min,"Drama, Romance, Thriller","In the 1920s, a newly married couple attempt t..."

In [33]:
df['date_added'] = pd.to_datetime(df['date_added'])

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5334 entries, 0 to 5350
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       5334 non-null   object
 1   type          5334 non-null   object
 2   title         5334 non-null   object
 3   director      5334 non-null   object
 4   cast          5334 non-null   object
 5   country       5334 non-null   object
 6   date_added    5334 non-null   datetime64[ns]
 7   release_year  5334 non-null   object
 8   rating        5334 non-null   object
 9   duration      5334 non-null   object
 10  listed_in     5334 non-null   object
 11  description   5334 non-null   object
dtypes: datetime64[ns](1), object(11)
memory usage: 670.8+ KB

In [35]:
df['release_year'] = df['release_year'].astype(int)

In [36]:
text_cols = ['type','title','director','cast','country','rating','listed_in']
for col in text_cols:
    df[col] = df[col].str.strip().str.lower()

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5334 entries, 0 to 5350
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       5334 non-null   object
 1   type          5334 non-null   object
 2   title         5334 non-null   object
 3   director      5334 non-null   object
 4   cast          5334 non-null   object
 5   country       5334 non-null   object
 6   date_added    5334 non-null   datetime64[ns]
 7   release_year  5334 non-null   int64
 8   rating        5334 non-null   object
 9   duration      5334 non-null   object
 10  listed_in     5334 non-null   object
 11  description   5334 non-null   object
dtypes: datetime64[ns](1), int64(1), object(10)
memory usage: 670.8+ KB

In [38]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [39]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5334 entries, 0 to 5350
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       5334 non-null   object
 1   type          5334 non-null   object
 2   title         5334 non-null   object
 3   director      5334 non-null   object
 4   cast          5334 non-null   object
 5   country       5334 non-null   object
 6   date_added    5334 non-null   datetime64[ns]
 7   release_year  5334 non-null   int64
 8   rating        5334 non-null   object
 9   duration      5334 non-null   object
 10  listed_in     5334 non-null   object
 11  description   5334 non-null   object
dtypes: datetime64[ns](1), int64(1), object(10)
memory usage: 670.8+ KB

In [43]:
df['title'].apply(type).value_counts()
df['country'].apply(type).value_counts()
df['cast'].apply(type).value_counts()

cast
<class 'str'>    5334
Name: count, dtype: int64

In [44]:
df['title'] = df['title'].astype(str)
df['country'] = df['country'].astype(str)
df['cast'] = df['cast'].astype(str)

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5334 entries, 0 to 5350
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       5334 non-null   object
 1   type          5334 non-null   object
 2   title         5334 non-null   object
 3   director      5334 non-null   object
 4   cast          5334 non-null   object
 5   country       5334 non-null   object
 6   date_added    5334 non-null   datetime64[ns]
 7   release_year  5334 non-null   int64
 8   rating        5334 non-null   object
 9   duration      5334 non-null   object
 10  listed_in     5334 non-null   object
 11  description   5334 non-null   object
dtypes: datetime64[ns](1), int64(1), object(10)
memory usage: 670.8+ KB

In [46]:
df = df[df['title'].str.contains('[a-zA-Z]', na=False)]
df = df[df['country'].str.contains('[a-zA-Z]', na=False)]
df = df[df['cast'].str.contains('[a-zA-Z]', na=False)]

In [47]:
df['title'] = df['title'].str.strip()
df['country'] = df['country'].str.strip()
df['cast'] = df['cast'].str.strip()

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5314 entries, 0 to 5350
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       5314 non-null   object
 1   type          5314 non-null   object
 2   title         5314 non-null   object
 3   director      5314 non-null   object
 4   cast          5314 non-null   object
 5   country       5314 non-null   object
 6   date_added    5314 non-null   datetime64[ns]
 7   release_year  5314 non-null   int64
 8   rating        5314 non-null   object
 9   duration      5314 non-null   object
 10  listed_in     5314 non-null   object
 11  description   5314 non-null   object
dtypes: datetime64[ns](1), int64(1), object(10)
memory usage: 539.7+ KB

In [49]:
data=pd.read_csv("/content/cleaned_netflix_titles .csv")

In [50]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5306 entries, 0 to 5305
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       5306 non-null   object
 1   type          5306 non-null   object
 2   title         5306 non-null   object
 3   director      5306 non-null   object
 4   cast          5306 non-null   object
 5   country       5306 non-null   object
 6   date_added    5306 non-null   object
 7   release_year  5306 non-null   int64
 8   rating        5306 non-null   object
 9   duration      5306 non-null   object
 10  listed_in     5306 non-null   object
 11  description   5306 non-null   object
dtypes: int64(1), object(11)
memory usage: 497.6+ KB